"""Modificata la tabella user, aggiunta colonna CF

Revision ID: 4f0baf85a451
Revises: 62b9eaa595e6
Create Date: 2026-02-27 10:57:56.727381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0baf85a451'
down_revision = '62b9eaa595e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('codiceFiscale',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('codiceFiscale',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)

    # ### end Alembic commands ###
