"""modifica tabella user

Revision ID: 552b7d4fcb60
Revises: ba1f8adaec60
Create Date: 2026-02-14 14:31:55.848798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552b7d4fcb60'
down_revision = 'ba1f8adaec60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blockChainId', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['blockChainId'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('blockChainId')

    # ### end Alembic commands ###
