"""Modificata la tabella user, aggiunta colonna CF

Revision ID: 62b9eaa595e6
Revises: 552b7d4fcb60
Create Date: 2026-02-27 10:53:39.767153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b9eaa595e6'
down_revision = '552b7d4fcb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codiceFiscale', sa.String(length=16), nullable=False))
        batch_op.create_unique_constraint(None, ['codiceFiscale'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codiceFiscale')

    # ### end Alembic commands ###
