"""Aggiunta tabella User

Revision ID: ba1f8adaec60
Revises: 
Create Date: 2026-02-09 11:31:04.977177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1f8adaec60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('cellularNumber', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'BIDDER', name='userroles'), nullable=False),
    sa.Column('passwordHash', sa.String(length=60), nullable=False),
    sa.Column('lastLoginAt', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
